apiVersion: v1
kind: Secret
metadata:
<<<<<<< HEAD
    name: {{ include "trino-gateway.fullname" . }}-configuration
=======
    name: trino-gateway-configuration
>>>>>>> 83d9fad (New squashed commit)
type: "Opaque"
data:
    config.yaml: "{{toYaml .Values.config | b64enc}}"
