apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trino-gateway.fullname" . }}-configuration
  labels:
    {{- include "trino-gateway.labels" . | nindent 4 }}
type: "Opaque"
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
