apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "trino-gateway.labels" . | nindent 4 }}
{{- $gatewayPort := "" }}
{{- if index .Values "config" "serverConfig" "http-server.http.enabled" }}
    {{- $gatewayPort = index .Values "config" "serverConfig" "http-server.http.port" }}
{{- end }}
{{- if index .Values "config" "serverConfig" "http-server.https.enabled" }}
{{- $gatewayPort = index .Values "config" "serverConfig" "http-server.https.port" }}
{{- end }}
{{- if empty $gatewayPort }}
{{- fail "Error: No port defined in serverConfig!" $gatewayPort }}
{{- end}}
{{- $portDefault := dict "port" $gatewayPort "targetPort" $gatewayPort }}
{{- $portValues := .Values.service.ports | default list | first | default $portDefault}}
{{- $_0 := set $portValues "port" $gatewayPort}}
{{- $_1 := set $portValues "targetPort" $gatewayPort}}
{{- $ports := list $portValues }}
{{- $additionalPorts := .Values.service.ports | default list | rest }}
{{- $allPorts := concat $ports $additionalPorts}}
{{- $spec := .Values.service }}
{{- $_2 := set $spec "ports" $allPorts }}
{{- $selectorLabels := include "trino-gateway.selectorLabels" . | fromYaml }}
{{- $_3 := set $spec "selector" $selectorLabels }}
spec: {{ $spec | toYaml | nindent 2}}
