repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
  - id: end-of-file-fixer
- repo: https://github.com/norwoodj/helm-docs
  rev:  v1.13.1
  hooks:
  - id: helm-docs-container
    args:
    - --chart-search-root=charts
    - --document-dependency-values
    - --sort-values-order=file
