
{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "trino.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus-operator
    {{- include "trino.labels" . | nindent 4 }}
    {{- if .Values.podMonitor.selector }}
    {{- toYaml .Values.podMonitor.selector | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "trino.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: jmx-exporter
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
