{{- if and (not .Values.auth.passwordAuthSecret) .Values.auth.passwordAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.passwordSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- if .Values.auth.passwordAuth }}
  password.db: {{ .Values.auth.passwordAuth | b64enc }}
{{- end }}
{{- end }}
---
{{- if and (not .Values.auth.groupsAuthSecret) .Values.auth.groups }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.groupsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- if .Values.auth.groups}}
  group.db: {{ .Values.auth.groups | b64enc }}
{{- end }}
{{- end }}
