{{- if contains "PASSWORD" .Values.server.config.authenticationType }}
{{- if .Values.auth.passwordAuth -}}
apiVersion: v1
kind: Secret
metadata:
  {{- if and .Values.auth .Values.auth.passwordAuthSecret }}
  name: {{ .Values.auth.passwordAuthSecret }}
  {{- else }}
  name: trino-password-authentication
  {{- end }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  password.db: {{ .Values.auth.passwordAuth | b64enc }}
  {{- if .Values.auth.groups}}
  group.db: {{ .Values.auth.groups | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
