{{- if or .Values.auth.passwordAuth .Values.auth.groups }}
apiVersion: v1
kind: Secret
metadata:
  {{- if and .Values.auth .Values.auth.passwordAuthSecret }}
  name: {{ .Values.auth.passwordAuthSecret }}
  {{- else }}
  name: trino-file-authentication
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
    {{- end }}
data:
{{- if .Values.auth.passwordAuth }}
  password.db: {{ .Values.auth.passwordAuth | b64enc }}
{{- end }}
{{- if .Values.auth.groups}}
  group.db: {{ .Values.auth.groups | b64enc }}
{{- end }}
{{- end }}
