{{- if .Values.server.catalogs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalog" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: catalog
data:
{{- range $key, $val := .Values.server.catalogs.configs }}
  {{ $key }}: | {{ $val | nindent 4 }}
{{- end }}
{{- end }}
