{{- if .Values.ingress.enabled }}
{{- $serviceName := printf "%s" ( include "trino.name" .) }}
{{- $servicePort := .Values.service.port }}
{{- $ingressPath := .Values.ingress.path }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "trino.fullname" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls: {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}