name: Release Trino Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/trino/**'
  workflow_dispatch: # manual to test

jobs:
  release:
    env:
      CHANGELOG_PATH: '${{ runner.temp }}/CHANGELOG.md'
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup node
        uses: AutoModality/action-clean@1.1.0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release Changelog Builder
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/changelog-config.json'
          outputFile: ${{ env.CHANGELOG_PATH }}
      - name: Inspect
        run: cat $CHANGELOG_PATH
