# This workflow syncs README to gh-pages branch and releases a new chart version
# when PRs are merged to main branch if no existing release for the chart
# version exists
name: Release Trino Chart

on:
  push:
    branches:
      - main

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy all README files from main to gh-pages
        run: |
          cd main
          # cp --parents preserves directory structure
          find . -name 'README.md' -exec cp --parents '{}' "../gh-pages/" ';'
      - name: Commit changes to gh-pages and push
        run: |
          cd gh-pages
          git add .
          git config user.name "GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          # Commit only if changes exist to avoid failure in this step
          git diff-index --quiet HEAD || git commit --signoff -m "Sync READMEs from main"
          git push

  release:
    needs: [sync-readme]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup node
        uses: AutoModality/action-clean@1.1.0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release Changelog Builder
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/changelog-config.json'
          outputFile: ${{ runner.temp }}/CHANGELOG.md
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NOTES_FILE: ${{ runner.temp }}/CHANGELOG.md
          # If we didn't bump the chart version then we can skip the release
          CR_SKIP_EXISTING: true
