name: Sync Readme

on:
  push:
    branches:
      - 'master'
    paths:
      - 'README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy README.md
        run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: commit
        run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name trino_community
          git config user.email "trino_community@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push
